# Generated by Django 2.1.dev20180207192815 on 2018-02-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180212_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner_list',
        ),
    ]
